ALTER TABLE games
    ADD COLUMN x_wins BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN o_wins BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN draws BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN round_number BIGINT NOT NULL DEFAULT 1,
    ADD COLUMN rematch_x_requested BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN rematch_o_requested BOOLEAN NOT NULL DEFAULT FALSE;
