name: test

# runs on push to main or pull request
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    # runs on the latest Ubuntu LTS (VM)
    runs-on: ubuntu-latest

    steps:
      # download the repo to the VM
      - name: Checkout repository
        uses: actions/checkout@v4

      # setup Go in the VM
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      # download the dependencies
      - name: Download dependencies
        run: go mod download

      # run the tests
      - name: Run tests
        run: go test ./...