name: test

# runs on push to main or pull request
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    # runs on the latest Ubuntu LTS VM
    runs-on: ubuntu-latest

    steps:
      # download the repo to the VM
      - name: Checkout repository
        uses: actions/checkout@v4

      # setup Go in the VM
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      # install protoc
      - name: Install protoc
        uses: arduino/setup-protoc@v3

      # install Go protobuf plugins
      - name: Install Go protobuf plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      # download the dependencies
      - name: Download dependencies
        run: go mod download

      # generate protobuf code
      - name: Generate protobuf code
        run: make proto

      # run all tests with race detector (including e2e tests)
      - name: Run tests with race detector
        run: go test -race ./...